version: '3.8'
services:
  db:
    image: postgres:15
    container_name: resume_db
    environment:
      POSTGRES_USER: resume_user
      POSTGRES_PASSWORD: resume_pass
      POSTGRES_DB: resume_screener
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./apps/backend
    container_name: backend
    command: sh -c "python /code/app/init_db.py && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - ./apps/backend:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build: 
      context: ./apps/frontend
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./apps/frontend:/app
      - /app/node_modules     
    working_dir : /app
    environment:
      - NODE_ENV=development

volumes:
  postgres_data:
